# Generated by Django 5.0.2 on 2024-02-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='mobile_phone',
            field=models.CharField(max_length=11),
        ),
    ]
