# Generated by Django 5.0.2 on 2024-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='emailVerificationCode',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='myuser',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
