# Generated by Django 5.0.2 on 2024-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_myuser_emailverificationcode_myuser_isemailverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=0, max_length=6)),
                ('expireTime', models.DateTimeField()),
            ],
        ),
    ]
