# Generated by Django 5.0.2 on 2024-03-07 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_useremailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='emailVerificationCode',
        ),
    ]
