# Generated by Django 5.0.2 on 2024-02-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_category_alter_myuser_is_active_project_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
